const Map<String, String> en = {
  'today': 'Today',
  'addTask': 'Add Task',
  'local': 'en',
  'noTask':
      'You do not have any tasks yet!\nAdd new tasks to make your day productive',
  'completed': 'Task Completed',
  'delete': 'Delete Task',
  'Cancle': 'Cancle',
  'Todo': 'TODO',
  'complete': 'Completed',
  'none': 'None',
  'dialy': 'Daily',
  'weekly': 'Weekly',
  'monthly': 'Monthly',
  'title': 'Title',
  'enterTitle': 'Enter Title here.',
  'note': 'Description',
  'enterNote': 'Enter Description here.',
  'date': 'Date',
  'startTime': 'Start Time',
  'endTime': 'End Time',
  'reimnd': 'Reimnd Before',
  'repeat': 'Repeat',
  'color': 'Color',
  'minutes': 'minutes',
  'hello': 'Hello',
  'newRimend': 'You have a new reminder',
  'task': 'Task',
  'requiredDate': 'Required Date',
  'Select Date are required': 'Select Date are required',
  'Select Time are required': 'Select Time are required',
  'Required': 'Required',
  'All fields are required': 'All fields are required',
  'Theme': 'Theme',
  'Setting': 'Setting',
  'Delete All Task': 'Delete All Task',
  'Cancle All Notification': 'Cancle All Notification',
  'App Languge': 'App Language',
  'App Color': 'App Color',
  'theme changed': 'App Theme changed successfully',
  'deleted task': 'All Task in App was Deleted',
  'cancle notification': 'All Notification of Tasks Are Closed',
  'app lang': 'App Language changed successfully',
  'app color': 'App Color changed successfully',
  'show task': 'Show Task',
  'good morning': 'Good Morning 😊',
  'good evining': 'Good Night 😴',
};
